#include<iostream.h>
#include<conio.h>

void main()
{
int r,c,i,j,n;
char ch='A';
char ch2='b';
 clrscr();
    for(r=1;r<=2;r++)
    {
    cout<<ch;

  for(c=1;c<=1;c++)
  {
    cout<<ch2;
     ch2++;
      cout<<ch2;
   char ch3=ch+3;
     cout<<ch3;
     char ch4=ch2+2;
     cout<<ch4;
     }
     cout<<endl;
    for(i=1;i<=5;i++)
    {
    cout<<i;

     }

     ch2='b';

     cout<<endl;
     }
getch();
}
