

#include<iostream.h>
#include<conio.h>

void main()
{
int r,c,i,j;
char ch='e';
char ch2='D';
 clrscr();
    for(r=1;r<=2;r++)
    {
    cout<<ch;//e

  for(c=1;c<=1;c++)
  {
    cout<<ch2;  //D
     ch=ch-2;
      cout<<ch; //c
     ch--;
     cout<<ch;//b
     char ch4=ch2-3;
     cout<<ch4;//A
     }
     cout<<endl;
    for(i=5;i>=1;i--)
    {
    cout<<i;

     }
     ch='e';
     ch2='D';

     cout<<endl;
     }
getch();
}
